### ISSUE TITLE
Significant lag once roaster is attatched

### ISSUE THREAD

**Issue by lodge93** [Roastero/Openroast#19]
There is a significant lag in the entire application that occurs once the roaster is attached.

**Comment by lodge93** [comment]
This has been resolved in v1.0.0

**Comment by jclif** [comment]
I'm still encountering considerable lag with and without the roaster attached.
